# Generated by Django 4.0.3 on 2022-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=50, null=True)),
                ('address_text', models.CharField(max_length=256, null=True)),
                ('address_value', models.JSONField(null=True)),
            ],
        ),
    ]
