# Generated by Django 4.0.3 on 2022-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='customer_phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='address_value',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
