# Generated by Django 4.0.3 on 2022-03-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_customer_phone_alter_report_address_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='address_value',
            field=models.JSONField(null=True),
        ),
    ]
