# Generated by Django 4.0.3 on 2022-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_address_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='address_value',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
